"""Add profile_image field to User model

Revision ID: 051077b31c5a
Revises: b9cad4f5d0ad
Create Date: 2024-08-23 21:03:34.466620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051077b31c5a'
down_revision: Union[str, None] = 'b9cad4f5d0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
