"""add_daily_challenge_meta_fields

Revision ID: 08f259d61572
Revises: f1a2b3c4d5e6
Create Date: 2025-12-25 14:09:06.922221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f259d61572'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_challenges', sa.Column('region', sa.String(), nullable=True))
    op.add_column('daily_challenges', sa.Column('subregion', sa.String(), nullable=True))
    op.add_column('daily_challenges', sa.Column('capital', sa.String(), nullable=True))
    op.add_column('daily_challenges', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('daily_challenges', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('daily_challenges', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('daily_challenges', sa.Column('languages', sa.String(), nullable=True))
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('daily_challenges', 'languages')
    op.drop_column('daily_challenges', 'population')
    op.drop_column('daily_challenges', 'longitude')
    op.drop_column('daily_challenges', 'latitude')
    op.drop_column('daily_challenges', 'capital')
    op.drop_column('daily_challenges', 'subregion')
    op.drop_column('daily_challenges', 'region')
    # ### end Alembic commands ###
