"""add_daily_challenge_meta_fields

Revision ID: 08f259d61572
Revises: f1a2b3c4d5e6
Create Date: 2025-12-25 14:09:06.922221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f259d61572'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Esta tabla se creó originalmente fuera de Alembic. La creamos cuando se
    # inicializa una instalación nueva y mantenemos el upgrade idempotente.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'daily_challenges' not in inspector.get_table_names():
        op.create_table(
            'daily_challenges',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('date', sa.Date(), nullable=False, unique=True),
            sa.Column('country_name', sa.String(), nullable=False),
            sa.Column('country_code', sa.String(), nullable=False),
            sa.Column('flag_image_bytes', sa.LargeBinary(), nullable=False),
            sa.Column('region', sa.String(), nullable=True),
            sa.Column('subregion', sa.String(), nullable=True),
            sa.Column('capital', sa.String(), nullable=True),
            sa.Column('latitude', sa.Float(), nullable=True),
            sa.Column('longitude', sa.Float(), nullable=True),
            sa.Column('population', sa.Integer(), nullable=True),
            sa.Column('languages', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
        )
        op.create_index('ix_daily_challenges_date', 'daily_challenges', ['date'])
    else:
        columns = {column['name'] for column in inspector.get_columns('daily_challenges')}
        for name, column_type in (
            ('region', sa.String()),
            ('subregion', sa.String()),
            ('capital', sa.String()),
            ('latitude', sa.Float()),
            ('longitude', sa.Float()),
            ('population', sa.Integer()),
            ('languages', sa.String()),
        ):
            if name not in columns:
                op.add_column('daily_challenges', sa.Column(name, column_type, nullable=True))
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('daily_challenges', 'languages')
    op.drop_column('daily_challenges', 'population')
    op.drop_column('daily_challenges', 'longitude')
    op.drop_column('daily_challenges', 'latitude')
    op.drop_column('daily_challenges', 'capital')
    op.drop_column('daily_challenges', 'subregion')
    op.drop_column('daily_challenges', 'region')
    # ### end Alembic commands ###
