"""Add max_score field to OverallScoreTable model

Revision ID: 70f7b1d66d9f
Revises: 71c48ccff8cf
Create Date: 2024-08-22 22:15:34.248175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f7b1d66d9f'
down_revision: Union[str, None] = '71c48ccff8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
