"""add groups jsonb to stage_runs and stage_best

Revision ID: 77842a3b385a
Revises: 8efe5849ed2b
Create Date: 2026-01-04 11:47:28.749962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77842a3b385a'
down_revision: Union[str, None] = '8efe5849ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Las tablas de carrera se introdujeron inicialmente mediante metadata,
    # no mediante una revisión. Crear su esquema base permite bootstrap limpio.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if 'career_user_stats' not in existing_tables:
        op.create_table(
            'career_user_stats',
            sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
            sa.Column('stages_completed', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('total_score', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('total_hints_used', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('total_time_seconds', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('last_activity_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
        )
        op.create_index('ix_career_ranking', 'career_user_stats', ['stages_completed', 'total_score', 'total_hints_used', 'total_time_seconds', 'last_activity_at'])
    if 'stage_best' not in existing_tables:
        op.create_table(
            'stage_best',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
            sa.Column('stage_id', sa.String(), nullable=False),
            sa.Column('score', sa.Integer(), nullable=False),
            sa.Column('hints_used', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('time_seconds', sa.Integer(), nullable=False),
            sa.Column('achieved_at', sa.DateTime(), nullable=False),
            sa.UniqueConstraint('user_id', 'stage_id', name='uix_user_stage_best'),
        )
        op.create_index('ix_stage_best_user_id', 'stage_best', ['user_id'])
        op.create_index('ix_stage_best_stage_id', 'stage_best', ['stage_id'])
    if 'stage_runs' not in existing_tables:
        op.create_table(
            'stage_runs',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
            sa.Column('stage_id', sa.String(), nullable=False),
            sa.Column('score', sa.Integer(), nullable=False),
            sa.Column('hints_used', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('time_seconds', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
        )
        op.create_index('ix_stage_runs_created_at', 'stage_runs', ['created_at'])
        op.create_index('ix_stage_runs_user_stage_created', 'stage_runs', ['user_id', 'stage_id', 'created_at'])

    op.alter_column('overall_score_table', 'region_key',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    inspector = sa.inspect(bind)
    if 'groups' not in {column['name'] for column in inspector.get_columns('stage_best')}:
        op.add_column('stage_best', sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    if 'groups' not in {column['name'] for column in inspector.get_columns('stage_runs')}:
        op.add_column('stage_runs', sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_runs', 'groups')
    op.drop_column('stage_best', 'groups')
    op.alter_column('overall_score_table', 'region_key',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'career'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
