"""add groups jsonb to stage_runs and stage_best

Revision ID: 77842a3b385a
Revises: 8efe5849ed2b
Create Date: 2026-01-04 11:47:28.749962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77842a3b385a'
down_revision: Union[str, None] = '8efe5849ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('overall_score_table', 'region_key',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('stage_best', sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('stage_runs', sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_runs', 'groups')
    op.drop_column('stage_best', 'groups')
    op.alter_column('overall_score_table', 'region_key',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'career'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
