"""Add OverallScoreTable model

Revision ID: 8b7b4bbf8505
Revises: b54b51eb0b61
Create Date: 2024-08-22 21:47:00.088391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7b4bbf8505'
down_revision: Union[str, None] = 'b54b51eb0b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
