"""leaderboard_region_support

Revision ID: 8efe5849ed2b
Revises: 08f259d61572
Create Date: 2026-01-01 10:40:32.345169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efe5849ed2b'
down_revision: Union[str, None] = '08f259d61572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overall_score_table', sa.Column('region_key', sa.String(), nullable=False, server_default='career'))
    op.add_column('overall_score_table', sa.Column('country_code', sa.String(), nullable=True))
    op.alter_column('overall_score_table', 'date_max_score',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('overall_score_table_user_id_key'), 'overall_score_table', type_='unique')
    op.create_index(op.f('ix_overall_score_table_country_code'), 'overall_score_table', ['country_code'], unique=False)
    op.create_index(op.f('ix_overall_score_table_region_key'), 'overall_score_table', ['region_key'], unique=False)
    op.create_unique_constraint('uix_user_region', 'overall_score_table', ['user_id', 'region_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_region', 'overall_score_table', type_='unique')
    op.drop_index(op.f('ix_overall_score_table_region_key'), table_name='overall_score_table')
    op.drop_index(op.f('ix_overall_score_table_country_code'), table_name='overall_score_table')
    op.create_unique_constraint(op.f('overall_score_table_user_id_key'), 'overall_score_table', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('overall_score_table', 'date_max_score',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('overall_score_table', 'country_code')
    op.drop_column('overall_score_table', 'region_key')
    # ### end Alembic commands ###
