"""leaderboard_region_support

Revision ID: 8efe5849ed2b
Revises: 08f259d61572
Create Date: 2026-01-01 10:40:32.345169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efe5849ed2b'
down_revision: Union[str, None] = '08f259d61572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column['name'] for column in inspector.get_columns('overall_score_table')}
    if 'region_key' not in columns:
        op.add_column('overall_score_table', sa.Column('region_key', sa.String(), nullable=False, server_default='career'))
    if 'country_code' not in columns:
        op.add_column('overall_score_table', sa.Column('country_code', sa.String(), nullable=True))
    if 'date_max_score' in columns:
        op.alter_column('overall_score_table', 'date_max_score',
                   existing_type=sa.DATE(),
                   type_=sa.DateTime(),
                   existing_nullable=True)

    constraints = {constraint['name'] for constraint in inspector.get_unique_constraints('overall_score_table')}
    legacy_constraint = op.f('overall_score_table_user_id_key')
    if legacy_constraint in constraints:
        op.drop_constraint(legacy_constraint, 'overall_score_table', type_='unique')
    if 'uix_user_region' not in constraints:
        op.create_unique_constraint('uix_user_region', 'overall_score_table', ['user_id', 'region_key'])

    indexes = {index['name'] for index in inspector.get_indexes('overall_score_table')}
    if op.f('ix_overall_score_table_country_code') not in indexes:
        op.create_index(op.f('ix_overall_score_table_country_code'), 'overall_score_table', ['country_code'], unique=False)
    if op.f('ix_overall_score_table_region_key') not in indexes:
        op.create_index(op.f('ix_overall_score_table_region_key'), 'overall_score_table', ['region_key'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_region', 'overall_score_table', type_='unique')
    op.drop_index(op.f('ix_overall_score_table_region_key'), table_name='overall_score_table')
    op.drop_index(op.f('ix_overall_score_table_country_code'), table_name='overall_score_table')
    op.create_unique_constraint(op.f('overall_score_table_user_id_key'), 'overall_score_table', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('overall_score_table', 'date_max_score',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('overall_score_table', 'country_code')
    op.drop_column('overall_score_table', 'region_key')
    # ### end Alembic commands ###
