"""empty message

Revision ID: 9ae9356ca9da
Revises: 280a7ef11e62
Create Date: 2024-08-10 14:30:14.136842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae9356ca9da'
down_revision: Union[str, None] = '280a7ef11e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _safe_drop_index(index_names, table_name: str, schema: str = "public"):
    """Drop index(es) solo si existen en la tabla dada."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names(schema=schema):
        existing = {ix["name"] for ix in insp.get_indexes(table_name, schema=schema)}
        for name in index_names:
            if name in existing:
                op.drop_index(name, table_name=table_name, schema=schema)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # cubrir ambos casos: nombre literal y con op.f(...) si existía convención
    _safe_drop_index({"ix_users_email", op.f("ix_users_email")}, "users")
    _safe_drop_index({"ix_users_username", op.f("ix_users_username")}, "users")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
