"""empty message

Revision ID: b235f38265c7
Revises: d531837758e4
Create Date: 2024-08-23 15:53:51.804415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b235f38265c7'
down_revision: Union[str, None] = 'd531837758e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overall_score_table', sa.Column('date_max_score', sa.Date(), nullable=True))
    op.add_column('overall_score_table', sa.Column('date_last_score', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overall_score_table', 'date_last_score')
    op.drop_column('overall_score_table', 'date_max_score')
    # ### end Alembic commands ###
