"""Add OverallScoreTable model

Revision ID: b54b51eb0b61
Revises: dddb061b9d8f
Create Date: 2024-08-22 21:45:48.615284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b54b51eb0b61'
down_revision: Union[str, None] = 'dddb061b9d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _safe_drop_index(index_names, table_name: str, schema: str = "public"):
    """Drop index(es) solo si existen en la tabla dada."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names(schema=schema):
        existing = {ix["name"] for ix in insp.get_indexes(table_name, schema=schema)}
        for name in index_names:
            if name in existing:
                op.drop_index(name, table_name=table_name, schema=schema)

def _safe_drop_table(table_name: str, schema: str = "public"):
    """Drop table sólo si existe (sin CASCADE)."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names(schema=schema):
        op.drop_table(table_name, schema=schema)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # cubrir ambos casos: nombre literal y con op.f(...) si existía convención
    _safe_drop_index({"ix_users_email", op.f("ix_users_email")}, "users")
    _safe_drop_index({"ix_users_full_name", op.f("ix_users_full_name")}, "users")
    _safe_drop_index({"ix_users_username", op.f("ix_users_username")}, "users")
    _safe_drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('profile_image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
