"""empty message

Revision ID: b9cad4f5d0ad
Revises: b235f38265c7
Create Date: 2024-08-23 16:53:16.570548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9cad4f5d0ad'
down_revision: Union[str, None] = 'b235f38265c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overall_score_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_overall_score_table_full_name', table_name='overall_score_table')
    op.drop_index('ix_overall_score_table_username', table_name='overall_score_table')
    op.create_foreign_key(None, 'overall_score_table', 'users', ['user_id'], ['id'])
    op.drop_column('overall_score_table', 'username')
    op.drop_column('overall_score_table', 'full_name')
    op.drop_column('overall_score_table', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overall_score_table', sa.Column('profile_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('overall_score_table', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('overall_score_table', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'overall_score_table', type_='foreignkey')
    op.create_index('ix_overall_score_table_username', 'overall_score_table', ['username'], unique=True)
    op.create_index('ix_overall_score_table_full_name', 'overall_score_table', ['full_name'], unique=False)
    op.drop_column('overall_score_table', 'user_id')
    # ### end Alembic commands ###
