"""Add last_score field to OverallScoreTable model

Revision ID: d531837758e4
Revises: 70f7b1d66d9f
Create Date: 2024-08-22 22:45:45.101776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd531837758e4'
down_revision: Union[str, None] = '70f7b1d66d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overall_score_table', sa.Column('last_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overall_score_table', 'last_score')
    # ### end Alembic commands ###
